# Generated by Django 5.2.7 on 2025-10-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('image', models.URLField(blank=True, null=True)),
                ('map_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
