# Generated by Django 5.2.7 on 2025-11-03 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
