# Generated by Django 5.2.7 on 2025-11-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
